### ISSUE TITLE
Home screen change

### ISSUE THREAD

**Issue by xak2** [youzarsiph/expo-react-native-paper#1]
How to change home screen from **(tabs)/index.tsx** to custom page?
Prop **initialRouteName** inside Stack ignores.

**Comment by youzarsiph** [comment]
## Adding a Custom Page

To implement a custom screen, please create a file named `app/index.tsx` and modify the `initialRouteName` to match `index`. This file will serve as your custom page.

## Using Drawer Navigation instead of Tab Navigation

To use drawer navigation, follow these steps:

1. Remove the `app/(tabs)` directory.
2. Rename the `app/drawer` directory to `app/(drawer)`.
3. Open the `app/_layout.tsx` file and eliminate the line containing `<Stack.Screen name='(tabs)' ... />`.
4. Replace `<Stack.Screen name='drawer' ... />` with `<Stack.Screen name='(drawer)' ... />`.
5. Adjust the `initialRouteName` to be `(drawer)`.

I trust this information will be helpful to you.
